# Aurora Light - Castor & Pollux Theme Collection

[cursor]
color = eff1f5 dc8a78

[colors]
background = eff1f5
foreground = 4c4f69
selection-foreground = 4c4f69
selection-background = ccd0da

## Normal/regular colors (color palette 0-7)
regular0 = 5c5f77
regular1 = d20f39
regular2 = 40a02b
regular3 = df8e1d
regular4 = 1e66f5
regular5 = 8839ef
regular6 = 179299
regular7 = acb0be

## Bright colors (color palette 8-15)
bright0 = 6c6f85
bright1 = d20f39
bright2 = 40a02b
bright3 = df8e1d
bright4 = 1e66f5
bright5 = ea76cb
bright6 = 04a5e5
bright7 = bcc0cc
