# Castor Georgia Tech - Castor & Pollux Theme Collection

[cursor]
color = 001528 B3A369

[colors]
background = 001528
foreground = c0c8d8
selection-foreground = c0c8d8
selection-background = 003057

## Normal/regular colors (color palette 0-7)
regular0 = 0d2640
regular1 = e06070
regular2 = 6cc490
regular3 = B3A369
regular4 = 4a88c0
regular5 = a080c8
regular6 = 50b0c0
regular7 = c0c8d8

## Bright colors (color palette 8-15)
bright0 = 3a5878
bright1 = f08090
bright2 = 90d8aa
bright3 = c8bd86
bright4 = 70a8d8
bright5 = baa0dd
bright6 = 70c8d5
bright7 = ffffff
