# Castor Slate - Castor & Pollux Theme Collection

[cursor]
color = 1e2028 58a6ff

[colors]
background = 1e2028
foreground = c9d1d9
selection-foreground = c9d1d9
selection-background = 1f6feb

## Normal/regular colors (color palette 0-7)
regular0 = 21262d
regular1 = ff7b72
regular2 = 7ee787
regular3 = e3b341
regular4 = 58a6ff
regular5 = bc8cff
regular6 = 79c0ff
regular7 = b1bac4

## Bright colors (color palette 8-15)
bright0 = 484f58
bright1 = ffa198
bright2 = a5d6a7
bright3 = f3e5ab
bright4 = 79c0ff
bright5 = d2a8ff
bright6 = a5d6ff
bright7 = f0f6fc
