# Castor Flagship - Castor & Pollux Theme Collection

[cursor]
color = 041A3B FFC005

[colors]
background = 041A3B
foreground = F2F2F2
selection-foreground = F2F2F2
selection-background = FFC005

## Normal/regular colors (color palette 0-7)
regular0 = 0C2E58
regular1 = E1321A
regular2 = 6AB017
regular3 = FFC005
regular4 = 729FCF
regular5 = EC0048
regular6 = 2AA7E7
regular7 = F2F2F2

## Bright colors (color palette 8-15)
bright0 = 3A5A80
bright1 = FF361E
bright2 = 7BC91F
bright3 = FFD00A
bright4 = 0071FF
bright5 = FF1D62
bright6 = 4BB8FD
bright7 = ffffff
