# Castor Azure - Castor & Pollux Theme Collection

[cursor]
color = 0d1621 66b3ff

[colors]
background = 0d1621
foreground = e0f0ff
selection-foreground = e0f0ff
selection-background = 3399ff

## Normal/regular colors (color palette 0-7)
regular0 = 1a2b42
regular1 = ff668c
regular2 = 52d9c4
regular3 = cce0ff
regular4 = 3399ff
regular5 = 99ccff
regular6 = 66b3ff
regular7 = cfe5ff

## Bright colors (color palette 8-15)
bright0 = 385573
bright1 = ff85a3
bright2 = 75ead9
bright3 = e6f0ff
bright4 = 52adff
bright5 = b3d9ff
bright6 = 85c7ff
bright7 = ffffff
