# Castor Cerulean - Castor & Pollux Theme Collection

[cursor]
color = 0a1420 60b8e0

[colors]
background = 0a1420
foreground = e0f0f8
selection-foreground = e0f0f8
selection-background = 00a0d8

## Normal/regular colors (color palette 0-7)
regular0 = 183040
regular1 = f06080
regular2 = 40d8a0
regular3 = e8c860
regular4 = 00a0d8
regular5 = a880d8
regular6 = 40c8f0
regular7 = c8e0f0

## Bright colors (color palette 8-15)
bright0 = 386080
bright1 = ff80a0
bright2 = 60f0b8
bright3 = f8d870
bright4 = 40c0f8
bright5 = c0a0f0
bright6 = 60e0ff
bright7 = ffffff
