# Castor Arctic - Castor & Pollux Theme Collection

[cursor]
color = 0c1520 a8d8ff

[colors]
background = 0c1520
foreground = e3f2ff
selection-foreground = e3f2ff
selection-background = 5db3ff

## Normal/regular colors (color palette 0-7)
regular0 = 19293d
regular1 = ff8fb3
regular2 = 7dffd4
regular3 = d1eaff
regular4 = 5db3ff
regular5 = c7e3ff
regular6 = a8d8ff
regular7 = d4e8ff

## Bright colors (color palette 8-15)
bright0 = 3d5975
bright1 = ffadc7
bright2 = 9cffe3
bright3 = e8f4ff
bright4 = 7dcaff
bright5 = dff0ff
bright6 = c7e3ff
bright7 = ffffff
