# Castor Ink - Castor & Pollux Theme Collection

[cursor]
color = 0c1420 a080d0

[colors]
background = 0c1420
foreground = d0d0e0
selection-foreground = d0d0e0
selection-background = 383858

## Normal/regular colors (color palette 0-7)
regular0 = 1c2838
regular1 = e07090
regular2 = 70c8a0
regular3 = e0a050
regular4 = 7090d0
regular5 = a080d0
regular6 = 70b0c8
regular7 = d0d0e0

## Bright colors (color palette 8-15)
bright0 = 506080
bright1 = f098b0
bright2 = 98e0c0
bright3 = f0c080
bright4 = 98b0e0
bright5 = c0a8e8
bright6 = 98d0e0
bright7 = ffffff
