# Castor Deep Ocean - Castor & Pollux Theme Collection

[cursor]
color = 0a1520 3dd9ff

[colors]
background = 0a1520
foreground = d9f0ff
selection-foreground = d9f0ff
selection-background = 20b8d8

## Normal/regular colors (color palette 0-7)
regular0 = 16293a
regular1 = ff577f
regular2 = 3fffa8
regular3 = ffdb70
regular4 = 3dd9ff
regular5 = 8cd4ff
regular6 = 5dffc7
regular7 = c5e8f7

## Bright colors (color palette 8-15)
bright0 = 3a5566
bright1 = ff799c
bright2 = 6fffbf
bright3 = ffe68f
bright4 = 63e5ff
bright5 = a6e0ff
bright6 = 82ffd6
bright7 = ffffff
