# Material Light - Castor & Pollux Theme Collection

[cursor]
color = ffffff 4285F4

[colors]
background = ffffff
foreground = 202124
selection-foreground = 202124
selection-background = 4285F4

## Normal/regular colors (color palette 0-7)
regular0 = 202124
regular1 = EA4335
regular2 = 34A853
regular3 = FBBC04
regular4 = 4285F4
regular5 = A142F4
regular6 = 24C1E0
regular7 = f8f9fa

## Bright colors (color palette 8-15)
bright0 = 5f6368
bright1 = F44336
bright2 = 0F9D58
bright3 = F9AB00
bright4 = 1A73E8
bright5 = 9334E6
bright6 = 00ACC1
bright7 = ffffff
