# Nocturne Dark - Castor & Pollux Theme Collection

[cursor]
color = 011627 f9e2af

[colors]
background = 011627
foreground = d6deeb
selection-foreground = d6deeb
selection-background = 1d3b53

## Normal/regular colors (color palette 0-7)
regular0 = 011627
regular1 = f38ba8
regular2 = a6e3a1
regular3 = f9e2af
regular4 = 89b4fa
regular5 = cba6f7
regular6 = 94e2d5
regular7 = d6deeb

## Bright colors (color palette 8-15)
bright0 = 4b6479
bright1 = eba0ac
bright2 = a6e3a1
bright3 = f9e2af
bright4 = 89b4fa
bright5 = f5c2e7
bright6 = 94e2d5
bright7 = ffffff
