# Pollux Patina - Castor & Pollux Theme Collection

[cursor]
color = 0c1614 50b8a0

[colors]
background = 0c1614
foreground = b8ccc6
selection-foreground = b8ccc6
selection-background = 50b8a0

## Normal/regular colors (color palette 0-7)
regular0 = 1e322c
regular1 = c86858
regular2 = 50b8a0
regular3 = c88060
regular4 = 5898c0
regular5 = a080b8
regular6 = 48b0b8
regular7 = b8ccc6

## Bright colors (color palette 8-15)
bright0 = 3e5e54
bright1 = e08878
bright2 = 70d0b8
bright3 = e0a080
bright4 = 78b0d0
bright5 = bca0d0
bright6 = 68c8d0
bright7 = e8f0ec
