# Pollux Ironside - Castor & Pollux Theme Collection

[cursor]
color = 081820 E07030

[colors]
background = 081820
foreground = E0E8EC
selection-foreground = E0E8EC
selection-background = E07030

## Normal/regular colors (color palette 0-7)
regular0 = 102838
regular1 = E04840
regular2 = 40C870
regular3 = E07030
regular4 = 3890D0
regular5 = B860C8
regular6 = 30B8C8
regular7 = E0E8EC

## Bright colors (color palette 8-15)
bright0 = 385060
bright1 = F07068
bright2 = 68E090
bright3 = F09050
bright4 = 60A8E0
bright5 = D080E0
bright6 = 58D0D8
bright7 = ffffff
