# Pollux CLI Light - Castor & Pollux Theme Collection

[cursor]
color = FAFAFA 383A42

[colors]
background = FAFAFA
foreground = 383A42
selection-foreground = 383A42
selection-background = C2E0F4

## Normal/regular colors (color palette 0-7)
regular0 = 383A42
regular1 = E45649
regular2 = 50A14F
regular3 = C18401
regular4 = 0184BC
regular5 = A626A4
regular6 = 0997B3
regular7 = FAFAFA

## Bright colors (color palette 8-15)
bright0 = 9DA5B4
bright1 = E45649
bright2 = 50A14F
bright3 = C18401
bright4 = 4078F2
bright5 = A626A4
bright6 = 0997B3
bright7 = FAFAFA
