# Pollux Abyss - Castor & Pollux Theme Collection

[cursor]
color = 080b12 4fc3f7

[colors]
background = 080b12
foreground = c5d3e8
selection-foreground = c5d3e8
selection-background = 29b6f6

## Normal/regular colors (color palette 0-7)
regular0 = 111926
regular1 = ef5350
regular2 = 69f0ae
regular3 = ffd740
regular4 = 29b6f6
regular5 = b388ff
regular6 = 4fc3f7
regular7 = 9eb3c7

## Bright colors (color palette 8-15)
bright0 = 3d4d5e
bright1 = ff8a80
bright2 = b9f6ca
bright3 = ffe57f
bright4 = 81d4fa
bright5 = d1c4e9
bright6 = 80deea
bright7 = eceff1
