# Castor Deep Ocean - Castor & Pollux Theme Collection

background #0a1520
foreground #d9f0ff
cursor #3dd9ff
selection_background #20b8d844
selection_foreground #0a1520

color0 #16293a
color1 #ff577f
color2 #3fffa8
color3 #ffdb70
color4 #3dd9ff
color5 #8cd4ff
color6 #5dffc7
color7 #c5e8f7
color8 #3a5566
color9 #ff799c
color10 #6fffbf
color11 #ffe68f
color12 #63e5ff
color13 #a6e0ff
color14 #82ffd6
color15 #ffffff
