# Material Light - Castor & Pollux Theme Collection

background #ffffff
foreground #202124
cursor #4285F4
selection_background #4285F433
selection_foreground #ffffff

color0 #202124
color1 #EA4335
color2 #34A853
color3 #FBBC04
color4 #4285F4
color5 #A142F4
color6 #24C1E0
color7 #f8f9fa
color8 #5f6368
color9 #F44336
color10 #0F9D58
color11 #F9AB00
color12 #1A73E8
color13 #9334E6
color14 #00ACC1
color15 #ffffff
